### ISSUE TITLE
Flickering buttons

### ISSUE THREAD

**Issue by krizf** [xx450/jTime#2] opened 2017-09-19 06:37 UTC
From time to time, the order of the buttons seems to change a for a fraction of a second, which causes a disturbing "flickering" effect. If the button in question is "active one" it is noticable

**Comment by xx450** [comment] 2017-09-19 08:47
@krizf do you remember exact steps that you did prior this issue has occurred? I'm unable to reproduce it.

**Comment by xx450** [comment] 2017-09-19 19:10
please remind if you still experience "the flickering" issue..

**Comment by xx450** [comment] 2019-11-21 21:01
I have not experienced any issue with this for a long time.... so closing

**Closed as completed by xx450** 2019-11-21 21:01 UTC
